# Generated by Django 6.0.3 on 2026-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ano', models.IntegerField()),
                ('foto_perfil', models.URLField()),
                ('curso', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
    ]
