# Generated by Django 6.0.3 on 2026-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilizador_rename_category_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('id_utilizador', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
                ('preco', models.CharField(max_length=50)),
                ('local_entrega', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('foto', models.URLField()),
                ('ativo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('id_utilizador', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
                ('preco', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.URLField()),
                ('ativo', models.IntegerField(default=1)),
            ],
        ),
    ]
