# Generated by Django 6.0.3 on 2026-03-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilizador', models.IntegerField()),
                ('id_servico', models.IntegerField()),
                ('estrelas', models.IntegerField()),
            ],
        ),
    ]
