# Generated by Django 6.0.3 on 2026-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_utilizador_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilizador', models.IntegerField()),
                ('id_servico', models.IntegerField(blank=True, null=True)),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='user',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='id_curso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilizador',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
