# Generated by Django 6.0.3 on 2026-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_utilizador_user_id_utilizador_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilizador', models.IntegerField()),
                ('id_produto', models.IntegerField(blank=True, null=True)),
                ('id_servico', models.IntegerField(blank=True, null=True)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
